spring.application.name=EcoRoute

# Configuracion de la Base de Datos (Usa variables de entorno para CubePath)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecoroute}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Api key OSR
ors.api.key=${ORS_API_KEY}

# Puerto de la aplicacion (CubePath suele usar el 8080)
server.port=${PORT:8080}

# Activar Virtual Threads (Project Loom) para que cada peticion sea un hilo virtual
spring.threads.virtual.enabled=true

